# Generated by Django 5.2.7 on 2025-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
