# Generated by Django 5.2.7 on 2025-11-17 16:26

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Напр., 'Основная DWH'", max_length=255)),
                ('engine', models.CharField(choices=[('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.mysql', 'MySQL'), ('django.db.backends.sqlite3', 'SQLite')], default='django.db.backends.postgresql', max_length=255)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(max_length=255, verbose_name='Имя БД')),
                ('db_user', models.CharField(max_length=255, verbose_name='Логин (read-only)')),
                ('db_password', encrypted_fields.fields.EncryptedTextField(help_text='Пароль будет зашифрован')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли этот источник?')),
                ('last_inspected', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя инспекция')),
            ],
            options={
                'verbose_name': '1. Источник данных',
                'verbose_name_plural': '1. Источники данных',
            },
        ),
        migrations.CreateModel(
            name='SchemaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('description_ru', models.TextField(blank=True, help_text="Напр.: 'Фактические расходы на ТВ, Радио, OOH...'", null=True, verbose_name='Бизнес-описание (для ИИ)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Включить эту таблицу для ИИ?')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ai_core.datasource')),
            ],
            options={
                'verbose_name': '2. Курируемая Таблица',
                'verbose_name_plural': '2. Курируемые Таблицы',
                'unique_together': {('data_source', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(editable=False, max_length=100)),
                ('is_metric', models.BooleanField(default=False, help_text='Это Метрика (число, напр. SUM, COUNT)?', verbose_name='Метрика?')),
                ('is_dimension', models.BooleanField(default=False, help_text='Это Измерение (категория, напр. GROUP BY)?', verbose_name='Измерение?')),
                ('description_ru', models.TextField(blank=True, help_text="Напр.: 'Фактические расходы в USD', 'Город (Астана, Алматы)'", null=True, verbose_name='Бизнес-описание (для ИИ)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Включить эту колонку для ИИ?')),
                ('schema_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ai_core.schematable')),
            ],
            options={
                'verbose_name': '3. Курируемый Столбец',
                'verbose_name_plural': '3. Курируемые Столбцы',
                'unique_together': {('schema_table', 'column_name')},
            },
        ),
    ]
