# Generated by Django 5.2.7 on 2025-11-19 16:10

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension # <-- Импорт

class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='schemacolumn',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='schematable',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='is_dimension',
            field=models.BooleanField(default=False, help_text='Это Измерение?', verbose_name='Измерение?'),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='is_metric',
            field=models.BooleanField(default=False, help_text='Это Метрика?', verbose_name='Метрика?'),
        ),
    ]
