# Generated by Django 5.2.7 on 2025-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_schemacolumn_embedding_schematable_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematable',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Включить эту таблицу для ИИ?'),
        ),
    ]
